spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
